import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Canvas } from "@react-three/fiber"
import Experience from "../components/Experience"

export default function Home() {
  return (
    <>
      <Head>
        <title>3d_01</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Canvas
          camera={{
            fov: 45,
            near: 0.1,
            far: 200,
            position: [0.8, 0.4, 6],
          }}
        >
          <Experience />
        </Canvas>
      </main>
    </>
  )
}
